apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: infrastructure
    app.kubernetes.io/part-of: argocd-apps
spec:
  project: default
  source:
    repoURL: https://github.com/Fizic/deploy-test.git
    targetRevision: master
    path: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
