apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  labels:
    app.kubernetes.io/name: openebs
    app.kubernetes.io/part-of: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://openebs.github.io/charts
    targetRevision: "4.2.0"
    chart: openebs
    helm:
      values: |
        ndm:
          enabled: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
        localpv:
          enabled: true
        legacy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
    retry:
      limit: 3
