apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: services
spec:
  project: services
  source:
    repoURL: https://github.com/Fizic/deploy-test.git
    targetRevision: master
    path: services/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
