apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: services
spec:
  project: services
  source:
    repoURL: https://github.com/Fizic/deploy-test.git
    targetRevision: master
    path: services/plane
  destination:
    server: https://kubernetes.default.svc
    namespace: plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 30m
