apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docmost
  namespace: argocd
  labels:
    app.kubernetes.io/name: docmost
    app.kubernetes.io/part-of: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  dependsOn:
    - name: cert-manager-issuer
  source:
    repoURL: https://github.com/Fizic/deploy-test.git
    targetRevision: HEAD
    path: apps/11-docmost
  destination:
    server: https://kubernetes.default.svc
    namespace: docmost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
    retry:
      limit: 3
