# Services Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak/app.yaml
  - keycloak/db-secret.yaml
  - vault/app.yaml
  - gitlab/app.yaml
  - gitlab/db-secret.yaml
  - gitlab/redis-secret.yaml
  - docmost/app.yaml
  - docmost/db-secret.yaml
  - docmost/redis-secret.yaml
  - docmost/app-secret.yaml
  - plane/app.yaml
  - plane/db-secret.yaml
  - plane/redis-secret.yaml
  - plane/app-secret.yaml

namespace: services
