apiVersion: v1
kind: Secret
metadata:
  name: plane-redis-secret
  namespace: plane
type: Opaque
stringData:
  password: change-me-in-production
  url: redis://:change-me-in-production@redis-master.plane.svc.cluster.local:6379
