# GitLab Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/part-of: services
spec:
  project: services
  source:
    repoURL: https://charts.gitlab.io
    chart: gitlab
    targetRevision: "8.*"
    helm:
      valueFiles:
        - values.yaml
      ignoreMissingValueFiles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 30m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
