{{- if .Values.gitlab.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitlab.source.repoURL }}
    chart: gitlab
    targetRevision: {{ .Values.gitlab.source.targetRevision }}
    helm:
      values: |
        global:
          hosts:
            domain: {{ .Values.domain }}
            https: true
          ingress:
            configureCertmanager: false
            class: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            tls:
              enabled: true
              secretName: gitlab-tls
        certmanager:
          install: false
        nginx-ingress:
          enabled: false # Use cluster ingress controller
        prometheus:
          install: false # Save resources unless asked
        gitlab-runner:
          install: true # Usually needed
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
