{{- if .Values.keycloak.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.keycloak.source.repoURL }}
    path: bitnami/keycloak
    targetRevision: {{ .Values.keycloak.source.targetRevision }}
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: keycloak.{{ .Values.domain }}
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          tls: true
          extraTls:
            - hosts:
                - keycloak.{{ .Values.domain }}
              secretName: keycloak-tls
        global:
          image:
            registry: public.ecr.aws
        image:
          registry: public.ecr.aws
          repository: bitnami/keycloak
        postgresql:
          image:
            registry: public.ecr.aws
            repository: bitnami/postgresql
            tag: 17
        auth:
          adminUser: admin
          # adminPassword: "changeMe123!" # Optional: Set a fixed password or use existingSecret
        # production: true # Enable for production (caching, etc)
        proxy: edge # Important for running behind Ingress/TLS termination
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
