apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  KEYCLOAK_DATABASE_PASSWORD: change-me-in-production
  postgres-password: change-me-in-production
