apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: loadbalancer

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: ingress

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: certificate-management

---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    app.kubernetes.io/name: openebs
    app.kubernetes.io/component: storage

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: gitops

---
apiVersion: v1
kind: Namespace
metadata:
  name: services
  labels:
    app.kubernetes.io/name: services
    tier: backend

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: observability

---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/component: backup

---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    tier: backend

---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: vault
    tier: backend

---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    tier: backend

---
apiVersion: v1
kind: Namespace
metadata:
  name: docmost
  labels:
    app.kubernetes.io/name: docmost
    tier: backend

---
apiVersion: v1
kind: Namespace
metadata:
  name: plane
  labels:
    app.kubernetes.io/name: plane
    tier: backend
