apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  dependsOn:
    - name: cert-manager-issuer
  source:
    repoURL: https://helm.plane.so
    targetRevision: "1.5.0"
    chart: plane/plane-ce
  destination:
    server: https://kubernetes.default.svc
    namespace: plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
    retry:
      limit: 3
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
